services:
  bot:
    image: node:22.11.0-alpine
    container_name: bot
    working_dir: /opt/src/app
    volumes:
      - .:/opt/src/app
      - node_modules:/opt/src/app/node_modules 
    environment:
      - NODE_ENV=dev
    command: sh -c "npm install -g pnpm && pnpm install --silent && pnpm run start:dev"
    networks:
      - cine_pantano_network
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
      - db
    restart: unless-stopped
  api:
    build:
      context: ../cinePantanoApplication
      dockerfile: Dockerfile
    container_name: api
    working_dir: /opt/src/app
    networks:
      - cine_pantano_network
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DB_NAME=pantano
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=mariadbrootPW
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_USER=user
      - AMQP_PASSWORD=rabbitmqPW
      - JWT_SECRET=secret
      - JWT_ISSUER=issuer
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-cine-pantano
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: rabbitmqPW
    networks:
      - cine_pantano_network
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: mariadbPW
      MARIADB_ROOT_PASSWORD: mariadbrootPW
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cine_pantano_network
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3

volumes:
  rabbitmq-data:
    driver: local
  mariadb-data:
    driver: local
  node_modules:
    driver: local

networks:
  cine_pantano_network:
    driver: bridge

